markdown: redcarpet
highlighter: pygments

remote_theme: vsoch/docsy-jekyll
url: mcfriend99.github.io
baseurl: /

title: qi
tagline: ' testing framework for Blade programming language.'

logo_pixels: 34
color: "#9c0eaf"
accentColor: purple # purple, green, etc.
themeColor: purple # purple, green, blue, orange, purple, grey
fixedNav: 'true' # true or false
feedback: true

